#!/bin/sh

# Set these paths appropriately

BIN=/home/carmen/git/source-language-recognition/tools/tagger/bin
CMD=/home/carmen/git/source-language-recognition/tools/tagger/cmd
LIB=/home/carmen/git/source-language-recognition/tools/tagger/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/utf8-tokenize.perl
ABBR_LIST=${LIB}/dutch-abbreviations
PARFILE=${LIB}/dutch-utf8.par

$TOKENIZER -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
