#!/bin/sh

# Set these paths appropriately

BIN=/home/carmen/git/source-language-recognition/tools/tagger/bin
CMD=/home/carmen/git/source-language-recognition/tools/tagger/cmd
LIB=/home/carmen/git/source-language-recognition/tools/tagger/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/italian-abbreviations
PARFILE=${LIB}/italian-utf8.par

$TOKENIZER -i -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
